### ISSUE TITLE
Len of group in search_group keeps changing by a lot

### ISSUE THREAD

**Issue by stefano-baruffaldi** [sosia-dev/sosia#13]
The len of group in test_search_group went from 310 to 223 in a few days. This seems a lot. Still, all rest goes through.

**Comment by Michael-E-Rose** [comment]
Why these labels?

**Comment by Michael-E-Rose** [comment]
It might be related to having (had) journal queries with duplicate entries, resulting from a buggy version of scopus.

**Comment by Michael-E-Rose** [comment]
Do you still experience these inconsistencies?

**Comment by stefano-baruffaldi** [comment]
I haven´t check recently. I will. But it may be related to the Dennis bug right?

**Comment by Michael-E-Rose** [comment]
Yes, but it can also be related so something else. Do you still have the code that produced this bug?
