### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by Michael-E-Rose** [sosia-dev/sosia#14]
In one way or the other, we need to implement [logging](https://docs.python.org/3/howto/logging.html).

At the very least, it should log which query is beging performed.  Another interesting aspect might be to log timings.

**Comment by Michael-E-Rose** [comment]
Users would enable logging like so:

```
import logging

logging.getLogger('sosia').setLevel(logging.DEBUG)
```

This is going to store all all SQLite queries and Scopus queries to a file.

**Comment by Michael-E-Rose** [comment]
@nils-herrmann Can you please take this over?

It guess it is straightforward, since only few functions are affected. When users activate the DEBUG level, all queries made by sosia should be logged to a file called `debug.txt`. Store it in the usual `~/.cache/sosia/` folder. All queries means: all SQLite queries and all Scopus queries. After each query, store the number of results. Make the output such that each block of queries is visually separable from the next.

**Comment by nils-herrmann** [comment]
Here is an overview of the implementation:
- I implemented one logger for the whole library defined in `sosia/utils/logger.py`.
- Each log follows the syntax`'%(asctime)s - %(levelname)s: %(message)s'`:
  ```log
  2024-10-25 14:44 - INFO - sosia - Stored information for 99,210 sources as well as 241,648 field-source 
  ```
- Logs are saved in `~/.cache/sosia/sosia.log`.
- I used three levels of logs:
   - DEBUG: For all pybliometrics search queries and `pd.read_sql_query()` 
   - INFO: For all previous print statements
   - CRITICAL: For all critical errors
