### ISSUE TITLE
Add author information already available when other information search is turned off

### ISSUE THREAD

**Issue by stefano-baruffaldi** [sosia-dev/sosia#18]
The additional information right now is provided only if information is set to True, which leads to additional download of abstract and references. But some information is already freely available which is not in the output if information is set to False. 
An easy change to have always at least some info

**Comment by stefano-baruffaldi** [comment]
This has been now implemented partly, for the publication information up to the given year, and for the stacked path. It should be extended to add information on NAME and other info from the AuthorSearch

**Comment by Michael-E-Rose** [comment]
Since we're using a separate method to inform matches, which re-uses already collected data, this issue has become obsolete.
