### ISSUE TITLE
Add indicators of authors quality based on forward citations

### ISSUE THREAD

**Issue by stefano-baruffaldi** [sosia-dev/sosia#20]
It can be done by looking for REF(eid) and counting citations in a window of time (for both focal and matches author). 
It would be very nice to have, but also very demanding as many queries would be used and it would take time.

**Comment by Michael-E-Rose** [comment]
It could be done even faster with the `CitationsOverview()` class of scopus, but this requires a special API key.

**Comment by stefano-baruffaldi** [comment]
This can be done now much more easily and efficiently using the query_size() function. It should be enough to build a function that queries the list of papers that cite the papers of an author and are published before the year provided (REF(eid OR eid OR ...) AND PUBYEAR BEF X) and get only the size result
