### ISSUE TITLE
Simplify query joiner 

### ISSUE THREAD

**Issue by stefano-baruffaldi** [sosia-dev/sosia#4]

**Comment by Michael-E-Rose** [comment]
If the reduced query (just using "OR") is sufficient:
- Everywhere where `_stacked_query()` is being used: Remove `"joiner"` entry from `params`.
- In `_stacked_query()`, remove joiner from list of parameters and also in the `params` object in the second part of the function

**Comment by stefano-baruffaldi** [comment]
It turns out, OR withing "( )" does not work for "AU-ID". 
Issue simplified keeping `"joiner"` and changing to `" OR "` for sources
